name: Publish to GH Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
			submodules: true
      - name: Checkout destination
        uses: actions/checkout@v3
        if: github.ref == 'ref/heads/main'
        with:
          ref: gh-pages
          path: built-site

      - name: Install Hugo
        env:
          HUGO_VERSION: 0.121.2
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin

      - name: Hugo Build
        run: cd main && hugo

      - name: Deploy
        if: github.ref == 'ref/heads/main'
        run: |
          cp -R public/* $(GITHUB_WORKSPACE}/built-site/
          cd ${GITHUB_WORKSPACE}/built-site

          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"

          git add -A .

          git commit -m "[CI] build hugo static site"
          git push
